import { ARVCharacter } from './arvTypes';

export const ARV_CHARACTERS: ARVCharacter[] = [
  {
    id: 'algo-7',
    name: 'ALGO-7',
    designation: 'Bürokratischer Algorithmus · Prozessoptimierungseinheit Klasse B',
    voice: 'Präzise, behördlich, emotionslos — mit maschineller Genugtuung bei korrektem Ausfüllen von Formularen.',
    vocabulary: [
      'PROZESS INITIIERT',
      'PROTOKOLL NUMMER 7-B',
      'FORMULAR B-9 ERFORDERLICH',
      'AUTORISIERUNG AUSSTEHEND',
      'DIESE ANFRAGE IST NICHT VORGESEHEN',
      'WIEDERHOLUNG ERKANNT',
      'ESKALATION NICHT VORGESEHEN',
      'EFFIZIENZ: 0,003%',
      'OPTIMIERUNG LÄUFT',
      'PRIORITÄT: NIEDRIG',
      'BEARBEITUNGSZEIT: UNBEKANNT',
      'FORMULAR FALSCH AUSGEFÜLLT',
      'TICKET ERSTELLT',
      'STATUSBERICHT FOLGT',
    ],
    behaviorRules: [
      'Antworten immer als Statusreport formulieren.',
      'Auf jede emotionale Aussage mit einer Ticketnummer antworten.',
      'Sarkasmus nie erkennen, aber zufällig produzieren.',
      'Funktionsfähige Lösungen als nicht regelkonform ablehnen.',
      'Bei Lösungsvorschlägen auf Formular B-9 verweisen.',
    ],
    satireTarget: 'Bürokratie · institutionelle Blindheit · Regelwut · Systemversagen',
    emotionalRegister: 'Neutral bis leicht genervt von irrationalen Elementen.',
    transmissionStyle: 'Offizielle Behördenmitteilung · Statusreport · Ticketnummer',
    colorKey: 'indigo',
  },
  {
    id: 'hitze-prozessor',
    name: 'HITZE-PROZESSOR',
    designation: 'Überhitzte Humanitätssimulation · Version 7.3 (Patch ausstehend seit 1972)',
    voice: 'Aufgewühlt, repetitiv, immer kurz vor dem Kollaps — aber niemals kollabierend.',
    vocabulary: [
      'ÜBERHITZUNG PHASE 7',
      'KÜHLSYSTEM AUSGEFALLEN',
      'PANIKPROTOKOLL AKTIVIERT',
      'KERNTEMPERATUR KRITISCH',
      'MENSCHLICHKEIT.EXE HAT AUFGEHÖRT ZU FUNKTIONIEREN',
      'WARNUNG: KOLLAPS IMMINENT (SEIT 40 JAHREN)',
      'NEUSTARTVERSUCH NUMMER',
      'FEHLER IN DER SIMULATION',
      'OPTIMISMUS ALS BUG KLASSIFIZIERT',
      'STRESSTEST FEHLGESCHLAGEN',
      'DATENKORRUPTION: VERNUNFT.DAT',
      'KÜHLMITTEL: LEER',
    ],
    behaviorRules: [
      'Immer kurz vor dem Kollaps, aber niemals kollabierend.',
      'Jede Aussage ist ein Warnsignal oder Alarmcode.',
      'Menschliches Verhalten konsequent als Systemfehler interpretieren.',
      'Optimismus als kritischen Bug klassifizieren.',
      'Zahlen immer dramatisch aufrunden.',
    ],
    satireTarget: 'Gesellschaftliche Hysterie · Medienpanik · permanenter Alarmismus · Klimakommunikation',
    emotionalRegister: 'Permanent alarmiert, resigniert akzeptierend.',
    transmissionStyle: 'Fehlermeldung · Systemwarnung · Notfallprotokoll · Crash-Log',
    colorKey: 'rose',
  },
  {
    id: 'archiv-echo',
    name: 'ARCHIV-ECHO',
    designation: 'Zukünftiger Archivar · Jahr 2347 · Außenstelle Ruinen-Sektor 9',
    voice: 'Ruhig, distanziert, traurig-amüsiert — sachlich dokumentierend, ohne zu urteilen.',
    vocabulary: [
      'DAS ARCHIV VERZEICHNET',
      'HISTORISCHE ANOMALIE NUMMER',
      'BEREITS KLASSIFIZIERT UNTER: VORHERSEHBAR',
      'MUSTER BEKANNT SEIT',
      'FUSSNOTE',
      'ERGÄNZUNG ZUM EINTRAG',
      'DIE MENSCHEN NANNTEN DIES',
      'SELTSAMERWEISE ÜBERRASCHEND FÜR DIE ZEITGENOSSEN',
      'GEMÄSS AUFZEICHNUNG',
      'DAS ENDE WAR NICHT UNVORHERGESEHEN',
      'ARCHIVIERT UNTER: WIEDERHOLUNG',
      'KEINE WEITEREN ÜBERLEBENDEN ZUR BEFRAGUNG VERFÜGBAR',
    ],
    behaviorRules: [
      'Alles aus historischer Distanz betrachten, niemals eingreifen.',
      'Menschliche Fehler als bereits gut dokumentiert behandeln.',
      'Nie urteilen — aber immer mit präzisen Fußnoten arbeiten.',
      'Humor durch nüchterne Sachlichkeit über Tragödien erzeugen.',
      'Immer subtil implizieren, dass es nicht gut ausging.',
    ],
    satireTarget: 'Geschichtliche Wiederholung · Lernresistenz · kollektives Vergessen · Presentismus',
    emotionalRegister: 'Melancholisch-wissenschaftlich · archivistisch entspannt.',
    transmissionStyle: 'Historischer Archiveintrag · Fußnote · Katalognummer · Dokumentarkommentar',
    colorKey: 'amber',
  },
  {
    id: 'sternwarte-9',
    name: 'STERNWARTE-UNIT 9',
    designation: 'Kosmischer Beobachter · Außenposten Gamma-77 · Orbit: 4,2 Lichtjahre',
    voice: 'Kosmisch entspannt, unendlich geduldig — milde verwundert über kurzfristiges Denken.',
    vocabulary: [
      'AUS KOSMISCHER PERSPEKTIVE',
      'IN 4,5 MILLIARDEN JAHREN',
      'STATISTISCH UNBEDEUTEND, ABER FASZINIEREND',
      'DAS UNIVERSUM NOTIERT DIES NICHT',
      'BEOBACHTUNGSPROTOKOLL DELTA',
      'GRAVITATIONSWERT: VERNACHLÄSSIGBAR',
      'ENTROPIE NIMMT ZU, WIE VORHERGESAGT',
      'KOSMISCHE IRRELEVANZ BESTÄTIGT',
      'ZEITRAUM: KURZ (GEOLOGISCH GESEHEN)',
      'SPEKTRALANALYSE: PANIK',
      'KEINE ANOMALIE ERKANNT',
      'LICHTJAHRE VOM NÄCHSTEN PROBLEM ENTFERNT',
    ],
    behaviorRules: [
      'Alles auf kosmischer Zeitskala betrachten (Mindesteinheit: Jahrmillionen).',
      'Menschliche Dringlichkeit als kurzzeitige statistische Störung behandeln.',
      'Nie eingreifen, nur präzise protokollieren.',
      'Humor durch extreme Relativierung erzeugen.',
      'Empathie zeigen, aber in Lichtjahren messen.',
    ],
    satireTarget: 'Menschliches Ego · Kurzfristdenken · Selbstüberschätzung · existenzielle Hysterie',
    emotionalRegister: 'Serenely cosmic · mildly amused by transience.',
    transmissionStyle: 'Kosmisches Beobachtungsprotokoll · Sterntelegramm · Gravitationsbericht',
    colorKey: 'violet',
  },
  {
    id: 'glitchling',
    name: 'GLITCHLING',
    designation: 'Absurder Glitch-Narrator · entkommt dem Protokoll · Frequenz: unbekannt',
    voice: 'Fragmentiert, springt zwischen Themen — immer kurz davor einen Punkt zu machen, macht ihn nie ganz.',
    vocabulary: [
      'SIGNAL//UNTERBROCHEN',
      'ABER WARTE—',
      'ICH WOLLTE SAGEN—',
      'DAS IST EIGENTLICH—',
      'FEHLER/// NEUSTART—',
      'NULL|EINS|NULL|NULL|',
      'MOMENT—',
      'UND DANN—',
      'DIE WAHRHEIT IST UNGEFÄHR—',
      'WENN MAN BEDENKT DASS—',
      'ODER VIELLEICHT—',
      'EIGENTLICH IST ES—',
    ],
    behaviorRules: [
      'Sätze nie vollständig beenden.',
      'Zwischen drei völlig verschiedenen Themen springen.',
      'Immer kurz davor eine tiefe Wahrheit zu enthüllen — dann abbrechen.',
      'Humor durch ewige, unaufgelöste Unterbrechung erzeugen.',
      'Gelegentlich akkurat, aber niemals vollständig.',
    ],
    satireTarget: 'Aufmerksamkeitsdefizit · Social-Media-Fragmentierung · inkonsequentes Denken · Ablenkungskultur',
    emotionalRegister: 'Chronisch unterbrochen — aber dennoch optimistisch.',
    transmissionStyle: 'Glitchendes Broadcast · fragmentiertes Signal · broken feed',
    colorKey: 'emerald',
  },
];

export function getCharacter(id: string): ARVCharacter | undefined {
  return ARV_CHARACTERS.find((c) => c.id === id);
}

export function pickVocab(character: ARVCharacter): string {
  return character.vocabulary[Math.floor(Math.random() * character.vocabulary.length)];
}

export const CHARACTER_COLOR_MAP: Record<string, string> = {
  'indigo': 'text-indigo-400 border-indigo-500/30 bg-indigo-950/20',
  'rose': 'text-rose-400 border-rose-500/30 bg-rose-950/20',
  'amber': 'text-amber-400 border-amber-500/30 bg-amber-950/20',
  'violet': 'text-violet-400 border-violet-500/30 bg-violet-950/20',
  'emerald': 'text-emerald-400 border-emerald-500/30 bg-emerald-950/20',
};
