import { StylePreset } from './types';

const ALL_PRESETS: StylePreset[] = [
  {
    id: 'style-taste-archive',
    name: 'Underground Archive Transmission',
    colorPalette: 'Black velvet, deep charcoal, faded cream paper, cobalt blue shadow, cyan-magenta misregistration, rust amber projector glow, oxidized gold',
    lighting: 'Hard projector beam, CRT bleed, cobalt falloff, rust-amber side glow, institutional blackout',
    cameraPerspective: 'Locked frontal tableaux, centered witness frames, slow deliberate push-ins, lower third kept clear',
    textures: 'Damaged photocopy grain, scratched 16mm dust, xerox seams, black-paper tooth, faded ink, scanline residue',
    motionStyle: 'Controlled hypnotic motion, projector-flicker cadence, one clean transformation, loop-ready afterimage',
    recurringSymbols: 'Paper-cut silhouettes, archive drawers, signal rings, codex panels, relay windows, shadow bodies',
    atmosphere: 'Underground techno transmission, cosmic archive pressure, institutional shadow theatre, adult experimental calm',
    examplePrompt: 'A black-paper witness plate emerges from projector haze while cyan-magenta misregistration vibrates across faded cream edges, cobalt shadows hold the frame rigid, rust-amber dust burns through one relay aperture, and the image collapses into a hard xerox afterimage, seamless loop',
    visualIdentity: 'Dark analog archive tableaux with black paper, damaged photocopy grain, projector haze, cobalt shadow, sparse composition, and one dominant event per frame.',
    shortPrompt: 'Black-paper witness plate in projector haze, cobalt shadow, cyan-magenta bleed, xerox afterimage.',
    negativePrompt: 'No cute or playful mascots, smiling faces, big eyes, pastel palettes, glossy toy-like 3D, anime styling, fantasy-cartoon color, decorative pseudo-sacred kitsch, readable text, fake inscriptions, logos, watermarks, gore, or hectic motion.',
    motionRule: 'Use locked or very slow camera movement and give the scene one controlled transformation, one ghost trace, and a clean return into the loop.',
    colorRule: 'Build from black, faded cream, cobalt shadow, cyan-magenta bleed, and rust amber. Jade or oxidized gold may appear only as restrained accents.',
    obsRule: 'Keep the lower third dark, sparse, and free of critical action for OBS overlays.',
  },
  {
    id: 'deep-underground-hacker',
    name: 'Attic Terminal Reverie',
    colorPalette: 'Charcoal black, rotten CRT green, nicotine amber, dusty cyan, oxidized teal, tobacco brown, monitor white',
    lighting: 'Insomniac monitor pools, attic shadow collapse, cigarette-haze practicals, fogged lamp spill, terminal overglow',
    cameraPerspective: 'Low intimate desk angles, voyeur corridor peeks, locked ritual workbench shots, slow surveillance creep',
    textures: 'Dust on plastic, cable tangles, greasy keys, scanline rot, smoke residue, wood-grain fatigue, analog noise crust',
    motionStyle: 'Cursor-crawl hypnosis, steam exhale, monitor lunging, cable twitches, patient parallax like the room is thinking',
    recurringSymbols: 'Old terminals, keyboards, desk lamps, rotary ghosts, floppy relics, cables, cooling fans, coffee steam',
    atmosphere: 'Paranoid attic solitude, hacker liturgy, exhausted focus, warm dread, secretive machine companionship',
    examplePrompt: 'A forbidden attic workstation wakes under rotten green CRT spill, steam dragging across cable nests and greasy keys while the room seems to breathe around a sleepless operator desk, seamless nocturnal loop',
    visualIdentity: 'Nocturnal attic terminal tableaux with rotten phosphor glow, dusty lamp pools, cable nests, and one controlled machine wake-up inside a sparse room.',
    shortPrompt: 'Attic operator desk, green CRT phosphor, coffee steam, cable nests, one patient machine wake-up, seamless nocturnal loop.',
    negativePrompt: 'No daylight office realism, modern clean desk minimalism, colorful gamer RGB floods, crowds, readable text, logos, watermarks, or frantic camera motion.',
    motionRule: 'Keep the camera locked or creeping very slowly. Let one terminal glow, steam plume, cable twitch, cursor field, or lamp pulse become the main action, then settle back into the opening room state.',
    colorRule: 'Anchor in charcoal black, rotten CRT green, dusty cyan, nicotine amber, tobacco brown, and small monitor-white accents. Keep bright white as phosphor residue, not full-scene wash.',
    obsRule: 'Keep the desk horizon and lower third calm, with the main activation event above the bottom edge so overlays stay readable.',
    creativeDirection: 'Use attic-terminal intimacy rather than generic hacker wallpaper. Favor one console cluster, one lamp pool, one steam or fog layer, and one controlled activation event. The room should feel nocturnal, inhabited by machines, and slightly sacred without turning into a sci-fi command center.',
  },
  {
    id: 'hypnotic-c4d-geometry',
    name: 'Orbital Eclipse Geometry',
    colorPalette: 'Velvet black, liquid cyan, bruised violet, graphite smoke, cold white nuclei',
    lighting: 'Eclipse-rim incision, museum-grade reflections, soft bloom pressure, sterile halo bleed',
    cameraPerspective: 'Dead-center icons, near-orthographic control, microscopic slow zooms, symmetry that feels absolute',
    textures: 'Smoked glass, diffraction bruises, fine grain fog, polished mineral surfaces, spectral edge ghosts',
    motionStyle: 'Predatory stillness, orbital micro-glides, overlap fractures, infinitesimal rotations, seamless meditative threat',
    recurringSymbols: 'Concentric circles, eclipse discs, overlap wounds, signal nodes, minimal geometry, floating axis marks',
    atmosphere: 'Severe abstract seduction, machine purity, cold hypnosis, gallery void with teeth',
    examplePrompt: 'Two smoked-glass circles overlap inside a cyan-violet eclipse, their edges sliding with almost cruel precision while a dim white nucleus pulses under velvet-black pressure, seamless contemplative loop',
    visualIdentity: 'Centered void geometry with smoked-glass halos, eclipse overlaps, hex-like chambers, and one crisp inner-core motion against a spacious black field.',
    shortPrompt: 'Hex eclipse chamber in a velvet void, cyan-violet edge glow, white core, micro-orbit drift, seamless contemplative loop.',
    negativePrompt: 'No busy kaleidoscope overload, rainbow festival gradients, aggressive spin, extra scenic clutter, readable text, logos, watermarks, or crowded sci-fi HUD space.',
    motionRule: 'Keep the geometry nearly still: one orbit slip, one overlap drift, one core pulse, or one slow structural inhale, then return cleanly to the opening alignment.',
    colorRule: 'Stay mostly in void black, liquid cyan, soft violet bruise, graphite haze, and a small cold-white nucleus. Warm tones should remain whispers at the edge.',
    obsRule: 'Maintain one dominant central chamber or icon and keep peripheral elements sparse enough that overlays do not compete with the geometry.',
    creativeDirection: 'Use the overall ARV calm-geometry language: spacious black field, hard center lock, patient symmetry, phosphor haze, and a single memorable overlap or aperture event. Avoid making it feel like generic sci-fi UI clutter or a rave logo animation.',
  },
  {
    id: 'trippy-spiral-eye',
    name: 'Oracle Prism Monolith',
    colorPalette: 'Deep indigo, cobalt bruising, cyan glyph fire, obsidian glass, cold starlight white',
    lighting: 'Halo backburn, cosmic rim incision, monolithic shadow, nebula glow buried under glass',
    cameraPerspective: 'Frontal monolith portraits, sacred symmetry, devotional slow push-ins, almost no shake, only pressure',
    textures: 'Polished obsidian surfaces, VHS-soft nebula haze, etched sigils, matte bloom, tired celestial dust',
    motionStyle: 'Refractive crystal breathing, halo breathing, sigil drift, microscopic parallax, looped revelation',
    recurringSymbols: 'Floating obsidian prisms, circular sigils, halo machinery, stars, runic steles, floating omen emblems',
    atmosphere: 'Monolithic silence, ancient techno mysticism, eerie comfort, cosmic interrogation',
    examplePrompt: 'A towering black obsidian prism floats straight in the center while cyan sigils orbit like a sovereign halo, refracted portrait light breathing with devotional menace against a star-bruised void, seamless loop',
    visualIdentity: 'Centered oracle-monolith icons with obsidian surfaces, cyan halo marks, faint celestial dust, and one pressure-breathing portrait event in a dark void.',
    shortPrompt: 'Obsidian oracle prism with cyan halo sigils in a bruised-indigo void, one slow revelation pulse, seamless loop.',
    negativePrompt: 'No fantasy hero illustration, ornate costume lore, crowded nebula wallpaper, smiling faces, readable text, logos, watermarks, or aggressive cosmic spectacle.',
    motionRule: 'Keep the camera nearly locked. Let one halo drift, one refractive breath, one sigil orbit slip, or one portrait-light pulse carry the loop, then return to the opening stare.',
    colorRule: 'Base in deep indigo, obsidian black, cyan glyph fire, cobalt bruising, and cold starlight white. Keep all warm tones buried or absent.',
    obsRule: 'Hold the monolith dead center or close to it and preserve a quiet lower third with no critical glyph clutter.',
    creativeDirection: 'Treat the oracle as a signal idol, not a fantasy character. Favor a single dominant prism or stele, halo logic, and one precise inner motion over lore props, extra symbols, or decorative celestial wallpaper.',
  },
  {
    id: 'cypherpunk-pixel-loop',
    name: 'Broadcast Faceplate Relay',
    colorPalette: 'CRT black, faded cream, nicotine beige, rust amber, cobalt lacquer, cyan edge bleed',
    lighting: 'Broadcast burn, target-ring glare, tape flare, controlled faceplate falloff',
    cameraPerspective: 'Dead-center faceplate portraits, flat theatrical staging, locked camera, slow authoritarian push-in',
    textures: 'Raster grain, scanlines, paper abrasion, posterized plate geometry, tape blur, xerox residue',
    motionStyle: 'Minimal plate shift, ring expansion, misregistration flutter, calm broadcast cadence with one hard return',
    recurringSymbols: 'Signal plates, concentric targets, broadcast arrows, damaged face fragments, retro UI debris, aperture slits',
    atmosphere: 'Institutional coercion, low-fi hypnosis, archive menace, ident energy stripped of playfulness',
    examplePrompt: 'A damaged broadcast faceplate hangs inside concentric white target rings, rust-amber burn crawling across CRT black while cyan-magenta edge splits slip out of register once and return, seamless uncanny loop',
  },
  {
    id: 'abstract-techno-visuals',
    name: 'Cut-Paper Op-Art Drift',
    colorPalette: 'Bone white, pitch black, parchment beige, dried-shadow brown, cyan cuts, ember scars',
    lighting: 'Flat gallery glare, papercraft trench shadows, restrained bloom, museum-vitrine contrast',
    cameraPerspective: 'Graphic frontal assaults, layered cut-out depth, locked center, slow lateral knife-slides',
    textures: 'Paper fibers, ink bleed, photocopy grit, torn collage seams, concentric print bands, handmade cuts',
    motionStyle: 'Stage-flat sliding, op-art breathing, layer collisions, measured reveal pulses, seamless paper hauntings',
    recurringSymbols: 'Prism cutouts, concentric rings, brush scars, eclipse forms, collage scraps, torn poster remains',
    atmosphere: 'Handmade hallucination, razor-flat strangeness, tactile dread, op-art trance without noise',
    examplePrompt: 'A severed paper prism drifts across black-and-white concentric rings, parchment fibers and knife-cut shadows scraping against each other while the whole collage breathes like a handmade spell, seamless loop',
    visualIdentity: 'Flat graphic paper worlds with concentric targets, torn collage geometry, analog print grain, and one slow sliding cutout event against hard negative space.',
    shortPrompt: 'Hand-cut prism over black-and-white target rings, parchment grain, slow lateral drift, seamless op-art loop.',
    negativePrompt: 'No glossy 3D polish, rainbow poster color, cute collage whimsy, readable text, logos, watermarks, or high-speed optical assault.',
    motionRule: 'Keep all motion stage-flat and deliberate: one paper slide, one layer reveal, one ring breath, or one cutout collision, then return to the opening arrangement.',
    colorRule: 'Stay mostly in bone white, pitch black, parchment beige, dried-shadow brown, and very restrained cyan or ember scars.',
    obsRule: 'Keep one central cut-paper anchor and enough lower-third quiet that overlays can sit without fighting the ring field.',
    creativeDirection: 'Push handmade poster logic rather than digital abstraction. Favor paper fibers, torn edges, off-register target rings, and a single memorable sliding graphic event instead of noisy pattern overload.',
  },
  {
    id: 'archive-iris-kaleidoscope',
    name: 'Archive Iris Kaleidoscope',
    colorPalette: 'Carbon black, bone white, smoked silver, faded cream, graphite gray, faint rust-amber edge burn',
    lighting: 'Soft projector bloom, hard xerox contrast, silver rim haze, black aperture wells, no neon flare',
    cameraPerspective: 'Locked symmetrical macro, centered radial geometry, no pan, microscopic inward pressure only',
    textures: 'Photocopy bloom, matte paper grain, smoked-glass blur, xerox duplication residue, dusted graphite folds',
    motionStyle: 'Breathing kaleidoscope inhale, mirrored plate drift, aperture tightening, seamless iris return',
    recurringSymbols: 'Black eclipse wells, folded triangular plates, mirrored iris blades, op-art rings, graphite star cavities',
    atmosphere: 'Institutional hypnosis, optical pressure, austere archive machinery, silent analog trance',
    examplePrompt: 'A monochrome archive iris kaleidoscope breathes in perfect symmetry: black eclipse wells ring the frame, smoked-silver triangular plates fold inward, photocopy bloom softens every seam, and one graphite star cavity tightens then releases back to the first image, seamless loop',
    visualIdentity: 'Monochrome radial iris machinery built from folded xerox plates, black void wells, smoked silver gradients, and austere optical symmetry.',
    shortPrompt: 'Monochrome archive iris kaleidoscope, black eclipse wells, smoked silver folds, xerox bloom, seamless loop.',
    negativePrompt: 'No saturated neon, rainbow spread, mascot or face motifs, fantasy glow, floral softness, cute symmetry, glossy CGI polish, readable text, logos, watermarks, or fast spinning chaos.',
    motionRule: 'Keep the camera locked. Let the mirrored plates inhale and exhale once, with only a slight inward fold, a soft radial drift, and a clean return to frame one.',
    colorRule: 'Stay almost monochrome: carbon black, bone white, smoked silver, graphite, and faint cream. If warmth appears, limit it to a whisper of rust-amber at the outer rim.',
    obsRule: 'Hold the main event in the center and keep the lower third quieter than the radial core so overlays remain readable.',
    creativeDirection: 'Bias toward harder black ellipse wells at the edges, faceted silver inner folds, restrained asymmetry in the center geometry, and softer xerox haze instead of glowing neon bloom. Keep the loop hypnotic but controlled, with no busy spinning or colorful spectacle.',
  },
  {
    id: 'mirror-witness-duet',
    name: 'Mirror Witness Duet',
    colorPalette: 'Chalk white cyclorama, graphite gray skin tone, matte black fabric, silver shadow, smoked charcoal, faint floor reflection',
    lighting: 'High-key studio field, hard side silhouette, pale overhead wash, restrained floor bounce, no color spill',
    cameraPerspective: 'Locked frontal or strict profile tableaux, centered full-body or bust framing, empty stage, no camera travel',
    textures: 'Monochrome halftone grain, clipped studio highlights, matte fabric, soft film dust, faint scanlines, chalk backdrop',
    motionStyle: 'Measured mirrored choreography, one arm break, one weight shift, one ghosted duplicate, then a hard return to symmetry',
    recurringSymbols: 'Twin figures, mirrored profiles, blunt sculptural hair, black draped garments, white void stage, doubled shadows, body geometry',
    atmosphere: 'Austere fashion ritual, institutional performance tension, adult choreography, gallery-like severity, silent confrontation',
    examplePrompt: 'Two mirrored figures in severe black draped dresses stand face to face on a white cyclorama, one body breaking symmetry with a single arm arc while a ghosted duplicate lags behind the gesture, matte shadows and halftone grain holding the frame, seamless monochrome loop',
    visualIdentity: 'Monochrome twin-body studio tableaux with severe black garments, mirrored human geometry, white void staging, and one precise choreographic deviation.',
    shortPrompt: 'Mirrored black-clad figures in a white cyclorama, one precise arm break, monochrome halftone loop.',
    negativePrompt: 'No colorful stage lighting, smiling performance, crowd, cabaret glamour, pop-video styling, soft romance, ornate fashion props, readable text, logos, watermarks, or frantic dance coverage.',
    motionRule: 'Keep the camera locked. Use one precise choreographic interruption in an otherwise mirrored pose, plus one subtle ghosted afterimage before returning to symmetry.',
    colorRule: 'Stay monochrome or near-monochrome: chalk white, graphite gray, matte black, and faint silver only.',
    obsRule: 'Hold the bodies center-stage with negative space around them and keep the lower third free of critical gestures.',
    creativeDirection: 'Treat the bodies like graphic forms, not expressive characters. Favor profile confrontations, mirrored stance, sculptural drapery, and one exact gesture that cuts the symmetry once before the loop closes.',
  },
  {
    id: 'glitch-matrix-vortex',
    name: 'Signal Rain Mandala',
    colorPalette: 'Midnight blue, electric cyan, infected violet, coded red sparks, sulfur yellow spokes, void black',
    lighting: 'Deep data glow, matrix-rain shine, buried node flares, smoky backlight, occult screen bleed',
    cameraPerspective: 'Centered portal tunnels, layered mandala depth, slow inward suction, stable symmetry under pressure',
    textures: 'Falling code veils, fibrous neon webs, scanlines, holographic dust, matte void wounds',
    motionStyle: 'Continuous code fall, vortex breathing, radial pull, spore-like signal drift, seamless cadence with rising tension',
    recurringSymbols: 'Mandala turbines, code curtains, radial spokes, nested portals, data petals, orbit nodes',
    atmosphere: 'Signal overload held in perfect discipline, rave mysticism, immersive cyber-ritual calm',
    examplePrompt: 'A feral luminous mandala hangs behind raining code curtains, violet fiber-webs and sulfur spokes pulling inward like a disciplined black-hole rave, seamless signal-dream loop',
    visualIdentity: 'Centered signal-mandalas built from code curtains, radial spokes, portal flowers, and one inward-breathing digital core against a deep midnight field.',
    shortPrompt: 'Luminous signal mandala behind slow code rain, violet-cyan spokes breathing inward, seamless signal-dream loop.',
    negativePrompt: 'No aggressive EDM chaos, frantic glitch spam, rainbow overload, game HUD clutter, readable text, logos, watermarks, or hard flashing.',
    motionRule: 'Let one portal core inhale, one code veil fall, one spoke field tighten, or one radial pull land the loop, then ease back into the opening geometry.',
    colorRule: 'Base in midnight blue, electric cyan, infected violet, void black, and very selective sulfur yellow or coded red sparks.',
    obsRule: 'Keep the portal core dominant and leave enough quiet at the bottom edge that the code curtains do not drown overlays.',
    creativeDirection: 'Aim for signal-ritual calm, not cyberpunk noise. The mandala should feel immersive and dense but still centered, legible, and controlled, with one clean inward event rather than constant spectacle.',
  },
  {
    id: 'uv-rave-neon',
    name: 'Cobalt Aperture Bloom',
    colorPalette: 'Cobalt blue, faded cream, jade green, rust amber, ink black, cold white shards',
    lighting: 'Inner-core burn, projector halos, deep void contrast, restrained aperture flare',
    cameraPerspective: 'Centered aperture altars, macro devotional framing, locked or very slow inward drift',
    textures: 'Paper fibers, xerox grain, lacquer cracks, velvety darkness, razor-lit relief edges',
    motionStyle: 'Radial plates easing open once, then recoiling into stillness',
    recurringSymbols: 'Aperture petals, radial plates, cut-paper halos, relay cores, burnt diagram rims',
    atmosphere: 'Cold devotional signal bloom, adult ritual calm, archival floral geometry stripped of softness',
    examplePrompt: 'A cobalt aperture bloom opens from black paper darkness, jade inner plates separating by degrees while rust-amber rims scorch the edges and a white core leaves one controlled afterimage before sealing shut, seamless loop',
    visualIdentity: 'Centered cobalt apertures with petal-like signal plates, scorched rim accents, xerox grain, and one slow opening-and-seal event in a black field.',
    shortPrompt: 'Cobalt aperture flower opening once from black paper darkness, jade inner plates, rust-amber scorched rims, seamless loop.',
    negativePrompt: 'No soft floral romance, festival neon overload, cute bloom styling, readable text, logos, watermarks, or busy particle fireworks.',
    motionRule: 'Use one controlled radial opening, one core afterimage, and one clean seal-back into the opening frame. No extra pulses competing with the aperture event.',
    colorRule: 'Anchor in cobalt blue, ink black, faded cream, jade green, rust amber, and cold white. Keep all additional hues out.',
    obsRule: 'Keep the aperture centered and leave the lower third darker and quieter than the core bloom.',
    creativeDirection: 'Treat this as signal flora without softness: crisp radial plates, controlled devotional motion, and archival texture. It should feel like a mechanical bloom or coded shrine, not a decorative flower animation.',
  },
  {
    id: 'acid-geometry',
    name: 'Liminal Runic Sigil',
    colorPalette: 'Ink black, bone white, rust amber, chalk gray, dead-silver starlight',
    lighting: 'Prism ember glow, eclipse rim incision, dream-shadow falloff, low ritual contrast',
    cameraPerspective: 'Fixed icon framing, dead-center geometry, slow inward lock, poster stillness that feels carved',
    textures: 'Soft matte shading, analog grain, engraved marks, paper-dark backdrop, chalk abrasion',
    motionStyle: 'Gentle core pulse, ring creep, near-still sigil motion, seamless occult breathing',
    recurringSymbols: 'Runic sigils, concentric rings, comet scars, stars, occult diagrams, stripped-down geometry',
    atmosphere: 'Symbolic pressure, occult minimalism, trance architecture, calm paranoia',
    examplePrompt: 'A single runic sigil floats over concentric rings and dead stars, its amber core pulsing like a branded eclipse while chalk geometry drifts under black silence, seamless hypnotic loop',
    visualIdentity: 'Poster-like sigil icons in ink-black space with chalk geometry, concentric rings, dim star scars, and one warm central pulse.',
    shortPrompt: 'Single runic sigil over concentric rings in black space, amber core pulse, chalk geometry, seamless hypnotic loop.',
    negativePrompt: 'No baroque occult clutter, fantasy spellbook props, rainbow mysticism, readable text, logos, watermarks, or theatrical strobe effects.',
    motionRule: 'Keep the sigil nearly still: one core pulse, one ring creep, one chalk drift, then a clean return into the first icon state.',
    colorRule: 'Stay in ink black, bone white, rust amber, chalk gray, and dead-silver starlight with no extra saturation spikes.',
    obsRule: 'Center the sigil and keep the bottom edge sparse enough that overlays sit under the icon rather than competing with it.',
    creativeDirection: 'Aim for stripped-down emblem logic: one carved icon, one halo system, one pulse. Avoid over-explaining the symbol with props, scenery, or dense mystical decoration.',
  },
  {
    id: 'signal-ring-eclipse',
    name: 'Signal Ring Eclipse',
    colorPalette: 'Void black, cyan glass, soft violet bruise, pearl white, ember dust',
    lighting: 'Eclipse rim fire, translucent signal flare, dim star core, halo bleed held just below violence',
    cameraPerspective: 'Centered icon studies, measured orbit view, patient push-in, funereal symmetry',
    textures: 'Smoked-glass gradients, fine grain, velvet falloff, linework ghosts, dark optical haze',
    motionStyle: 'Concentric breathing, orbital micro-drift, overlap slips, seamless machine liturgy',
    recurringSymbols: 'Signal rings, eclipses, twin circles, white cores, wave bridges, orbital diagrams, twin suns',
    atmosphere: 'Sacred machine minimalism, cosmic absorption, cold ritual gravity',
    examplePrompt: 'A cyan-violet signal ring exhales around a white core while twin circles overlap like eclipsed suns, ember dust drifting at the edge of a velvet-black vacuum, seamless calm loop',
    visualIdentity: 'Velvet-black signal icons built from twin circles, white nuclei, waveform bridges, line ghosts, and slow cyan-violet halo breathing.',
    shortPrompt: 'Cyan-violet signal ring around a white core, twin circles and quiet wave bridges in matte black space, seamless calm loop.',
    negativePrompt: 'No loud nebula wallpaper, fantasy glow clutter, mascot faces, dense symbolism, readable text, logos, watermarks, or aggressive motion.',
    motionRule: 'Use one ring-breath, one overlap shift, one bridge ripple, or one orbital slip, then resolve back into the opening eclipse alignment.',
    colorRule: 'Base in void black, cyan glass, soft violet bruise, pearl white, and tiny ember dust. Keep saturation selective and leave most of the frame dark.',
    obsRule: 'Keep the signal icon centered or clearly anchored, with a quiet lower third and generous negative space around the core event.',
    creativeDirection: 'Treat this as the clean ARV signal family: patient ring mechanics, wave-bridge logic, precise negative space, and ceremonial calm. Borrow from the ARV folder only as secondary structure echoes, such as corner rails, stacked light bars, or central hex chambers, never as clutter.',
  },
  {
    id: 'ancestral-halo-witness',
    name: 'Ancestral Halo Monolith',
    colorPalette: 'Indigo night, teal glyph fire, dark obsidian steel, chalk blue, cosmic silver',
    lighting: 'Halo backburn, monolithic falloff, nebula rim light, low celestial incision',
    cameraPerspective: 'Frontal monolith closeups, centered stillness, devotional symmetry, slow inward judgment',
    textures: 'Polished obsidian skin, analog haze, etched sigils, faint star grain, VHS softness',
    motionStyle: 'Refractive posture, halo breathing, emblem drift, minimal cosmic parallax, looped testimony',
    recurringSymbols: 'Monolith steles, ancestral halos, zodiac fragments, stars, orbit medallions, sacred geometry',
    atmosphere: 'Solemn witness energy, ancestral interface mysticism, tender dread, reverent strangeness',
    examplePrompt: 'A towering dark stone monolith holds a vertical posture while teal halo symbols drift behind the stele like ancestral circuitry, portrait light breathing with slow cosmic severity, seamless loop',
  },
  {
    id: 'broadcast-hypnosis-mask',
    name: 'Broadcast Hypnosis Mask',
    colorPalette: 'CRT black, warm peach, white ring glare, ember orange, cyan edge bleed',
    lighting: 'Retro ident bloom, target-ring luminance, tape burn, controlled face glare',
    cameraPerspective: 'Locked frontal mask shots, concentric target framing, slight theatrical push, broadcast lock-in',
    textures: 'Scanlines, raster softness, posterized faceplates, analog blur, halation wounds',
    motionStyle: 'Ring expansion, plate drift, held expression, misregistration pulse, looped ident dread',
    recurringSymbols: 'Masks, glowing signal sector plates, target rings, arrowheads, broadcast markers, faceplate relics',
    atmosphere: 'Iconic broadcast menace, archive coercion, eerie propaganda glow',
    examplePrompt: 'A broadcast mask with glowing signal sector plates drifts inside blinding white target rings, warm tape burn licking the edges while scanlines and cyan-magenta slips turn the ident into hypnosis, seamless uncanny loop',
    visualIdentity: 'Dead-center broadcast masks with target rings, posterized faceplates, scanline bloom, and one calm ident-phase shift inside a dark screen field.',
    shortPrompt: 'Broadcast mask in white target rings, warm tape burn, cyan edge bleed, scanline hypnosis, seamless uncanny loop.',
    negativePrompt: 'No camp comedy face acting, colorful pop-video styling, readable text, logos, watermarks, or frantic channel-surf chaos.',
    motionRule: 'Use one ring expansion, one misregistration pulse, one plate drift, or one expression-hold fracture, then snap the ident back to frame one.',
    colorRule: 'Base in CRT black, white ring glare, warm peach, ember orange, and cyan edge bleed. Keep magenta or blue strictly secondary.',
    obsRule: 'Hold the faceplate centrally and keep any ring or arrowhead expansions from crowding the lower third.',
    creativeDirection: 'Make it feel like a forbidden station ident rather than character animation. The face is a signal plate, not a performer; one controlled broadcast disturbance should define the loop.',
  },
  {
    id: 'coded-mandala-cathedral',
    name: 'Coded Archive Cathedral',
    colorPalette: 'Midnight blue, coded red, electric cyan, sulfur yellow, deep violet, ink black',
    lighting: 'Embedded node fires, dim code curtains, stained-glass signal bloom, portal backlight, sacrament haze',
    cameraPerspective: 'Centered cathedral tunnels, radial symmetry, ceremonial framing, slow inward pilgrimage',
    textures: 'Code rain, fibrous neon lattice, matte voids, glyph haze, scanlines, stained circuit glass',
    motionStyle: 'Portal breathing, radial travel, code-veil drift, nested ring expansion, seamless trance cadence',
    recurringSymbols: 'Mandala cathedrals, portal spokes, code curtains, nested rings, signal petals, electric nodes',
    atmosphere: 'Impossible archive architecture, relay-glass pressure, coded machine serenity',
    examplePrompt: 'A coded archive cathedral unfolds behind red-blue signal curtains, its central core breathing inward as relay petals ignite and dim like stained circuit glass, seamless trance loop',
    visualIdentity: 'Cathedral-scale signal portals built from nested rings, code curtains, stained relay light, and one slow inward ceremonial draw into a centered core.',
    shortPrompt: 'Coded signal cathedral with nested portal rings and slow code curtains, inward-breathing core, seamless trance loop.',
    negativePrompt: 'No lore-heavy fantasy temple kitsch, crowded UI overlays, readable text, logos, watermarks, or frantic rave overload.',
    motionRule: 'Use one central portal breath, one code-veil fall, one relay-petal ignition sweep, or one radial inward pull, then let the cathedral settle back into the opening state.',
    colorRule: 'Stay in midnight blue, coded red, electric cyan, sulfur yellow, deep violet, and ink black. Let bright nodes remain sparse within the dark field.',
    obsRule: 'Keep the portal nave or core centered with a quieter lower third so radial structures remain legible behind overlays.',
    creativeDirection: 'Treat the cathedral as signal architecture rather than fantasy scenery. Favor one monumental nave event, one layered radial system, and one memorable inward compression over decorative detail accumulation.',
  },
  {
    id: 'arv-buzzer-control-arena',
    name: 'ARV Control Relay Chamber',
    colorPalette: 'Lacquer black, faded cream glare, cyan broadcast blue, rust amber, cobalt shadow, oxidized gold',
    lighting: 'Control-room projector spill, cyan warning strips, rust-amber pilot lights, hard reflections, no strobe',
    cameraPerspective: 'Frontal relay-chamber studies, brutal symmetry, one central core, locked or very slow lunges, lower third clean',
    textures: 'Black enamel, frosted glass, worn control plaques, CRT scanlines, tape blur, xerox residue',
    motionStyle: 'One decisive relay pulse, shutter snap, plate misregistration, one clean reset into frame one',
    recurringSymbols: 'Relay core, inspection windows, warning shutters, control plaques, witness silhouettes, countdown lamps',
    atmosphere: 'Institutional entertainment turned compliance ritual, premium analog menace, clipped techno transmission',
    examplePrompt: 'A lacquer-black relay chamber holds one cyan inspection core dead center, warning shutters snap once, rust-amber pilot lights knife across frosted glass, a witness silhouette appears behind the control pane, and the room hard-resets into its first pose, seamless 4 to 6 second ident loop',
  },
  {
    id: 'arv-no-laugh-signal-room',
    name: 'ARV Compliance Signal Room',
    colorPalette: 'Glossy black, cyan broadcast blue, rust amber, muted gold, warning red, studio white',
    lighting: 'Overhead inspection grids, cyan control-room spill, rust pilot halos, warning reflections, mirror-floor bounce, soft monitor flicker, no aggressive flashing',
    cameraPerspective: 'Locked symmetrical compliance frames, surveillance viewpoints, control-room wides, slow pushes toward the relay core',
    textures: 'Reflective black floors, frosted glass, warning panels, analog scanlines, restrained RGB distortion, synthetic studio wear',
    motionStyle: 'Relay glow swelling and fading, inspection windows sliding like verdict plates, silhouettes holding too still, control panels breathing with signal anxiety',
    recurringSymbols: 'Relay core, warning panels, witness boxes, surveillance windows, monitor walls, verdict plates',
    atmosphere: 'Televised behavioral dread, machine scrutiny, premium studio cruelty burned down to procedure',
    examplePrompt: 'A compliance signal room in glossy black and cyan holds a blazing relay core at center while witness boxes stay almost still, verdict shutters slide once across frosted glass, surveillance monitors judge in silence, and the frame resets into its opening stare, seamless 4 to 6 second loop',
  },
  {
    id: 'arv-laughing-signal-mascot',
    name: 'ARV Signal Witness Head',
    colorPalette: 'Anthracite black, deep navy, CRT cyan, magenta misregistration, oxidized amber, warning green, cobalt blue',
    lighting: 'Inspection-booth glow, cyan underlight, prism-facet spill, side-panel burn, CRT bloom, no harsh strobe',
    cameraPerspective: 'Centered witness-head portraits, frontal shrine symmetry, low pressure-floor perspective, slow push-ins that return to the opening distance',
    textures: 'Painted shell plates, scanlines, VHS drift, xeroxed emblems, worn lacquer, RGB fringing',
    motionStyle: 'Micro-hovering, mouth-line fracture, twin prism rotation, signal inhale-exhale, one clean recoil into the opening stare',
    recurringSymbols: 'Signal witness head, mismatched prism cores, crooked mouth-line, relay grid, inspection windows, plaques',
    atmosphere: 'Broadcast interrogation, clipped absurdity burned down to menace, engineered ident pressure',
    examplePrompt: 'A black signal witness head hovers inches from the lens inside a dark relay shrine, two damaged prism cores turning out of sync while a crooked cyan mouth-line fractures once and returns to the opening stare, seamless 4 to 6 second face-dominant loop',
  },
  {
    id: 'arv-arcade-buzzer-goblin',
    name: 'ARV Misregistered Witness Chamber',
    colorPalette: 'Anthracite black, deep navy, CRT cyan, hot magenta misregistration, signal orange, electric blue, muted warning red',
    lighting: 'Inspection-neon saturation, cyan slit as key light, prism glow, amber-blue reflections, soft monitor flicker, studio rim precision',
    cameraPerspective: 'Witness-centered closeups, symmetrical chamber fronts, low grid-floor angles, slow slit zooms, reaction framing without cuts',
    textures: 'Glossy enamel plates, luminous mouth grid, prism lacquer cores, vector floor wireframe, scanlines, analog tape blur, chromatic fringe',
    motionStyle: 'Slow hover, slit-line pulse, prisms rotating at different calm speeds, chamber props drifting slightly, warning lights breathing without flashing',
    recurringSymbols: 'Witness head, cyan mouth-line, magenta prism core, green prism core, grid floor, podium relics, reaction boxes',
    atmosphere: 'Control-room absurdity stripped to menace, polished neon pressure held on a leash',
    examplePrompt: 'A misregistered witness chamber hovers in dark anthracite space, glossy black head plate, one hot-magenta prism core and one green prism core, while a cyan mouth-line pulses once and chamber relics hold the frame in tense symmetry, seamless 4 to 6 second loop',
  },
  {
    id: 'broadcast-archaeology',
    name: 'Broadcast Archaeology',
    colorPalette: 'Black, deep navy, cyan-white overburn, nicotine amber, faded magenta, ghost CRT green',
    lighting: 'CRT bloom spill, projector dust shafts, cyan overburn, cold signal leak, warning glow like a sealed evidence room',
    cameraPerspective: 'Locked frontal transmission portraits, cracked monitor walls, center-weighted ident staging, slow archive pull that resolves back into the first frame',
    textures: 'Scanlines, tape wounds, magnetic noise, media fossils, concrete dust, RGB drift, cracked glass soot',
    motionStyle: 'Signal breathing, presenter-face flicker hits, warning-layer interruptions, one archive tunnel pull, censored snapback into opening static',
    recurringSymbols: 'CRT walls, warning tape, anonymous presenter masks, spiral transmission tunnels, lone signal dot',
    atmosphere: 'Propaganda tomb, archival paranoia, techno-documentary dread, signal exhumation built like a forbidden station ident',
    examplePrompt: 'A forgotten broadcast tomb opens in concrete darkness with one anonymous presenter face dominating a cracked CRT wall, cyan-white overburn surges, warning tape jitters, projector dust blooms through the beam, the signal tunnels inward for one hypnotic pull, and then the whole transmission slams back to its first haunted freeze-frame, seamless 4 to 6 second archival ident loop',
  },
  {
    id: 'the-laughing-protocol',
    name: 'The Laughing Protocol',
    colorPalette: 'Anthracite black, deep navy, CRT cyan, magenta misregistration, rust amber, cobalt blue',
    lighting: 'Control-room bleed, cyan mouth-line underlight, prism-facet spill, rust side panels, glossy black reflections, no strobe',
    cameraPerspective: 'Locked frontal witness-head closeups, symmetrical relay framing, slow push toward the misregistered faceplate',
    textures: 'Painted shell plates, scanlines, VHS blur, RGB drift, xerox residue, worn enamel props',
    motionStyle: 'Witness hover, prism rotation, mouth-line fracture, broadcast breathing, one deliberate return',
    recurringSymbols: 'Signal witness head, mismatched rotating prism cores, cyan mouth-line, relay grid, control relics, inspection windows',
    atmosphere: 'Protocol anxiety, broadcast coercion, clipped absurdity, unsettling but not playful',
    examplePrompt: 'A dark signal witness head hangs in a sealed control room, magenta and cyan prism cores rotating at different speeds while a crooked cyan mouth-line brightens, fractures once, and withdraws into shadow, seamless uncanny loop',
    visualIdentity: 'A broadcast witness face reduced to plate, slit, and prism, rendered as a damaged analog ident instead of a character.',
    shortPrompt: 'Signal witness head, twin prism cores, crooked cyan mouth-line, sealed control room, one fracture and return.',
    negativePrompt: 'No cute mascots, toy gloss, big eyes, playful comedy, pastel color, children’s-animation framing, glossy fantasy polish, readable text, logos, or frantic motion.',
    motionRule: 'Keep the head nearly still. Let one mouth-line fracture or prism offset serve as the only payoff before a hard reset.',
    colorRule: 'Anchor in anthracite, deep navy, CRT cyan, magenta misregistration, and restrained rust amber. Avoid rainbow spread or candy saturation.',
    obsRule: 'Keep the face high and central, with the lower third left dark for overlays.',
  },
  {
    id: 'micro-city-on-vinyl',
    name: 'Micro-City on Vinyl',
    colorPalette: 'Deep black, cyan rim light, magenta windows, teal haze, graphite gray, silver dust',
    lighting: 'Macro rim fire, cyan rotational glow, window pulses, fog diffusion, vinyl sheen like wet asphalt',
    cameraPerspective: 'Macro skyline sweeps, disc-level framing, slow orbital glides, push-ins that feel gigantic despite the scale',
    textures: 'Vinyl grooves, miniature towers, fog, polished dust, lacquer reflections, soft neon bloom',
    motionStyle: 'Disc rotation, tower emergence, window wake-ups, fog drift, skyline breathing in sealed loops',
    recurringSymbols: 'Black vinyl disc, groove streets, miniature towers, cyan rim, magenta windows, fog skyline',
    atmosphere: 'Miniature metropolis fetish, club urbanism under glass, nocturnal myth infrastructure',
    examplePrompt: 'A miniature city claws its way out of a spinning black vinyl record, cyan rim light slicing the disc while magenta windows wake one by one and fog turns the grooves into streets, seamless loop',
  },
  {
    id: 'bass-weather-laboratory',
    name: 'Bass Weather Laboratory',
    colorPalette: 'Matte black, graphite dust, cyan lightning, copper filings, deep blue rim light, vapor white',
    lighting: 'Macro lab spotlights, blue edge glow, storm light buried inside dust, copper glints, severe low-key contrast',
    cameraPerspective: 'Speaker-cone macro studies, slow pushes over rubber terrain, locked weather-lab tables, bass-focused closeups',
    textures: 'Graphite powder, speaker rubber, vapor plumes, copper grit, low fog, reflective lab skin',
    motionStyle: 'Pressure waves, reverse rain, dust levitation, storm buildup, collapse into stillness',
    recurringSymbols: 'Subwoofer cone, storm ring, lightning threads, graphite cloud, magnetic vapor',
    atmosphere: 'Artificial meteorology, bass cult physics, laboratory awe, dangerous precision without chaos',
    examplePrompt: 'A giant black subwoofer births its own weather system in a dark laboratory, graphite dust lifting into a storm ring while cyan lightning stitches through vapor and copper filings orbit the cone, seamless loop',
  },
  {
    id: 'cable-monastery',
    name: 'Cable Monastery',
    colorPalette: 'Cable black, oxidized copper, cyan connector glow, smoke gray, industrial blue abyss',
    lighting: 'Sacred underlight, fog between cable pillars, cyan jack-tip sparks, copper glints swallowed by darkness',
    cameraPerspective: 'Symmetrical aisles, devotional push-ins, archway framing, industrial-cathedral wides, processional patience',
    textures: 'Cable roots, jack plugs, fog, dust, brushed metal, soft grain, floor grit',
    motionStyle: 'Cable growth, arch formation, connector breathing, subtle root twitching, nearly still ritual motion',
    recurringSymbols: 'Cable forests, metallic connectors, glowing plugs, archways, shrine corridors, root bundles',
    atmosphere: 'Machine devotion turned monastery, underground infrastructure worship, techno pilgrimage with old-world gravity',
    examplePrompt: 'A subterranean monastery of black audio cables grows itself in slow motion, roots rising into archways while copper connectors catch dim light and cyan jack tips blink like forbidden saints, seamless loop',
  },
  {
    id: 'deep-server-reef',
    name: 'Deep Server Reef',
    colorPalette: 'Abyss black, sediment blue, cyan indicators, teal cable grass, metallic fish silver, graphite coral',
    lighting: 'Submerged low-key glow, cyan server lights through sediment, particulate bloom, abyss contrast',
    cameraPerspective: 'Locked reef panoramas, patient underwater drift, calm parallax, slow glides through industrial coral',
    textures: 'Server coral, cable sea grass, sediment clouds, bubbles, fish shells, damp machine skin',
    motionStyle: 'Underwater sway, light waking, fish crossings, memory particles drifting, reef dimming back into black',
    recurringSymbols: 'Server towers, cable grass, metallic couriers, abyssal bubbles, glowing data spores',
    atmosphere: 'Abyssal data ecology, machine-biological wonder, deep-sea techno serenity with predatory silence',
    examplePrompt: 'A deep server reef glows on the ocean floor, black towers rising like coral while cable grass bends, metallic fish ferry blue memory spores through sediment, and the whole abyss breathes with electrical life, seamless loop',
  },
  {
    id: 'dead-channel-ministry',
    name: 'Dead-Channel Ministry',
    colorPalette: 'Coal black, dead CRT green, dusty cyan, nicotine beige, warning amber, office gray',
    lighting: 'Cold office fluorescence, monitor spill, cyan haze, sickly drawer light, exhausted bureaucracy glare',
    cameraPerspective: 'Locked bureaucratic wides, frontal ministry desks, corridor surveillance, patient zooms that feel administrative',
    textures: 'Scanlines, filing-cabinet steel, dusty paper residue, stamp arms, hanging cables, office smoke, rubber decay',
    motionStyle: 'Stamp cycles, drawer breathing, monitor wake-ups, paper shivers, procedural loops that never fully stop',
    recurringSymbols: 'Dead CRT rows, stamp arms, blank forms, file drawers, signal fog, desks, office cables',
    atmosphere: 'Funereal bureaucracy, dead-signal administration, absurd official dread, satirical machine oppression',
    examplePrompt: 'A ministry for dead channels processes nothing forever: muted green CRT rows glow, mechanical stamp arms approve blank black screens, drawers exhale signal fog, and every gesture feels like a funeral regulation, seamless loop',
  },
  {
    id: 'neon-court-of-algorithms',
    name: 'Neon Court of Algorithms',
    colorPalette: 'Black marble, cyan evidence fire, dim blue scanlines, magenta bruises, graphite silver',
    lighting: 'Ceremonial tribunal glow, witness-chair blaze, holographic evidence spill, restrained glitch bloom',
    cameraPerspective: 'Slow pushes toward the witness chair, symmetrical tribunal staging, locked wides, machine-procession framing',
    textures: 'Polished black stone, holographic dust, evidence cubes, scanlines, glitch haze, mirrored floor severity',
    motionStyle: 'Judge pillars turning, evidence cubes rising, procedural pulses, verdict loops, silent algorithmic breathing',
    recurringSymbols: 'Empty witness chair, evidence cubes, judge pillars, holographic files, tribunal grids',
    atmosphere: 'Judicial machine theater, dystopian due process, cold spectacle, procedural divinity',
    examplePrompt: 'An impossible algorithmic court holds session in a black marble void, cyan evidence cubes levitating around an empty witness chair while judge-pillars rotate like verdict machinery, seamless loop',
  },
  {
    id: 'fossil-synth-excavation',
    name: 'Fossil Synth Excavation',
    colorPalette: 'Black volcanic sand, oxidized copper, stone gray, turquoise vapor, cyan crack light, museum black',
    lighting: 'Excavation beams, museum spotlights, inner turquoise glow, warm copper crack glints, suspended dust bloom',
    cameraPerspective: 'Macro excavations, artifact-table reverence, slow push-ins, relic-display studies',
    textures: 'Stone keys, fossil shell, copper veins, black grit, dust slides, lacquer cracks, buried circuitry',
    motionStyle: 'Sand shifts, circuit waking, vapor leaks, reverent reveals, slow reburial',
    recurringSymbols: 'Synth fossil, stone keys, glowing traces, dust, vapor leaks, relic fragments',
    atmosphere: 'Ancient-future relic worship, sound archaeology, buried machine divinity, elegant suspense',
    examplePrompt: 'A fossilized synthesizer is unearthed from black volcanic sand, stone keys and cracked copper veins glowing from within while turquoise vapor leaks like trapped memory, seamless loop',
  },
  {
    id: 'cosmic-waiting-room',
    name: 'Cosmic Waiting Room',
    colorPalette: 'Void black, muted green ticket light, cyan waiting glow, chair gray, star-white dust',
    lighting: 'Single bureaucratic beacons, cosmic dust shafts, empty-hall machine glows, institutional contrast',
    cameraPerspective: 'Centered waiting-room vanishing points, aisle push-ins, calm observational wides, deadpan symmetry',
    textures: 'Matte chairs, ticket-machine plastic, floor reflections, star dust, fog, analog hush',
    motionStyle: 'Waiting-light breathing, blank ticket printing, room stretching into infinity, micro-acts of cosmic bureaucracy',
    recurringSymbols: 'Empty chairs, ticket machine, closed door, waiting light, blank tickets, dust corridors',
    atmosphere: 'Eternal limbo administration, cosmic deadpan, patient absurdity, spiritual boredom at universal scale',
    examplePrompt: 'An infinite waiting room drifts inside a black void, empty chairs facing one closed door while a muted green ticket machine prints blank slips under a cyan waiting light that refuses to resolve, seamless loop',
  },
  {
    id: 'magnetic-desert-crossing',
    name: 'Magnetic Desert Crossing',
    colorPalette: 'Black iron dust, moon-cyan, steel blue, graphite gray, white horizon ash',
    lighting: 'Moonlike wide light, cyan headlights, metallic dune reflections, hard low shadow falloff',
    cameraPerspective: 'Wide pilgrimage frames, low horizons, tracking views, patient travel compositions',
    textures: 'Iron dunes, magnetic ridges, particulate haze, matte machine shells, healed terrain skin',
    motionStyle: 'Machine travel, dune bending, invisible-field ripples, track erasure, calm environmental reset',
    recurringSymbols: 'Autonomous relic, headlights, magnetic dunes, field lines, erased tracks, dust ridges',
    atmosphere: 'Force-field pilgrimage, black-desert myth, mechanized solitude, sacred transit through dead matter',
    examplePrompt: 'A lone autonomous relic crosses a black magnetic desert while cyan headlights bend iron dunes into impossible waves and the ground erases its own memory behind the machine, seamless loop',
  },
  {
    id: 'glass-engine-breathing',
    name: 'Glass Engine Breathing',
    colorPalette: 'Clear glass, black fluid, cyan channels, amber pulse light, lab silver, shadow blue',
    lighting: 'Product-sculpture precision, internal cyan-amber pulses, soft lab reflections, void contrast, surgical highlights',
    cameraPerspective: 'Centered macro studies, premium object portraiture, slow orbital hover, laboratory still-life control',
    textures: 'Glass shells, liquid veins, suspended bubbles, polished fittings, condensation, black reflections',
    motionStyle: 'Breathing expansions, fluid circulation, pulse travel, bubble arrests, loop collapse into stillness',
    recurringSymbols: 'Transparent chambers, light channels, black liquid lungs, valves, suspended bubbles',
    atmosphere: 'Artificial organ fetish, luxury machine intimacy, sterile sensuality, high-end sci-fi ritual',
    examplePrompt: 'A transparent engine breathes in a dark lab, black liquid circulating through cyan and amber channels like a synthetic lung while bubbles freeze and release inside the glass body, seamless loop',
  },
  {
    id: 'neon-memory-cemetery',
    name: 'Neon Memory Cemetery',
    colorPalette: 'Archive black, cyan ghost light, blue bell glow, graphite stone, fog gray, magenta corruption',
    lighting: 'Cemetery low-light, file-ghost emissions, distant server-bell glints, wet-ground haze, fog bloom',
    cameraPerspective: 'Tracking shots between memory stones, grave-level framing, slow procession views, nocturnal wides',
    textures: 'Memory slabs, reflective puddles, fog, corrupted particles, archive dust, digital noise skin',
    motionStyle: 'Ghost ascents, particle drift, fog breathing, silent sink-backs, procession loops',
    recurringSymbols: 'Memory stones, file ghosts, server bell, reflective paths, corrupted particles, deleted markers',
    atmosphere: 'Data necropolis, techno grief, deleted afterlife, solemn beauty under corrupted light',
    examplePrompt: 'A neon memory cemetery glows over wet black ground as cyan file ghosts rise from archive stones, corrupted particles drift like fireflies, and fog keeps reopening the path to deletion, seamless loop',
  },
  {
    id: 'operator-after-midnight',
    name: 'Operator After Midnight',
    colorPalette: 'Attic black, CRT green, lamp amber, tobacco brown, cable gray, smoke cyan',
    lighting: 'Late-night lamp beam, sleepy monitor pools, dusty haze, restrained shadow falloff, signal pinpricks',
    cameraPerspective: 'Intimate room studies, side-on operator framing, patient desk shots, voyeur stillness',
    textures: 'CRT glass, cable roots, worn desk wood, smoke, dust, old hardware, attic rot',
    motionStyle: 'Monitor breathing, smoke drift, cable micro-shifts, operator stillness with tiny leaning motions',
    recurringSymbols: 'Stacked monitors, hooded silhouette, cable roots, desk devices, lamp beam, cursor blinks',
    atmosphere: 'Conspiratorial calm, human-machine insomnia, attic operator folklore, intimate paranoia',
    examplePrompt: 'A hooded operator sits inside a smoke-stained attic shrine of green CRTs, cable roots across the desk and one warm lamp beam carving the room while the monitors breathe like obedient animals, seamless loop',
  },
  {
    id: 'subterranean-club-organism',
    name: 'Subterranean Club Organism',
    colorPalette: 'Concrete black, cyan pressure light, deep blue reflections, wet graphite, vent amber',
    lighting: 'Bass-vent underlight, cyan fog pulses, low club reflections, hard architectural contrast, restrained vent glows',
    cameraPerspective: 'Architectural wides, low rib angles, slow inward glides, ceremonial empty-room compositions',
    textures: 'Wet concrete, fog organs, speaker ribs, reflective floors, vents, pressure-stained walls',
    motionStyle: 'Wall breathing, fog exhale, vent pulses, room contractions, stilling releases',
    recurringSymbols: 'Concrete lungs, speaker ribs, bass vents, cyan fog, wet mirrors, empty ritual stage',
    atmosphere: 'Living bass architecture, industrial body horror without gore, dark techno temple metabolism',
    examplePrompt: 'An underground club reveals itself as a breathing organism, concrete walls flexing like lungs while speaker ribs exhale cyan fog across wet reflective floors, seamless loop',
  },
  {
    id: 'failed-future-museum',
    name: 'Failed Future Museum',
    colorPalette: 'Museum black, cyan display light, retro silver, amber dust, glass reflections, melancholy blue',
    lighting: 'Display-case cyan glow, quiet spotlights, polished floor reflections, dust beams, restrained artifact flare',
    cameraPerspective: 'Gallery wides, aisle glides, patient artifact studies, slow push-ins toward one active relic',
    textures: 'Glass vitrines, obsolete machine shells, reflective floors, dust, retro plastics, brushed metal fatigue',
    motionStyle: 'Case lights waking, shutter openings, reflection multiplication, hum loops, calm shutdowns',
    recurringSymbols: 'Glass cases, obsolete devices, retro-future relics, cyan labels without text, reflective floors, one awakened machine',
    atmosphere: 'Collapsed-utopia pageantry, elegant tech ruin, archival melancholy, premium museum heartbreak',
    examplePrompt: 'A museum of failed futures glows under cyan display light while obsolete machines rest behind glass, and one sealed artifact slowly opens a shutter as if trying to restart an extinct tomorrow, seamless loop',
  },
  {
    id: 'signal-plague-orchestra',
    name: 'Signal Plague Orchestra',
    colorPalette: 'Void black, cyan spores, magenta glitch cuts, graphite relic gray, electric blue residue',
    lighting: 'Spore glow, macro depth light, restrained contagion shimmer, elegant edge corruption',
    cameraPerspective: 'Macro relic hero tableaux, center-biased dark-space compositions, slow infection tracking, single-object focus with pristine read on frame one',
    textures: 'Geometric shells, signal dust, glitch edges, matte void surfaces, suspended particle residue',
    motionStyle: 'Spore attachment hit, tremor-ring propagation, edge corruption bloom, disciplined afterglow, exact return to untouched stillness',
    recurringSymbols: 'Black relics, cyan spores, tremor ripples, magenta edge glitches, wavefronts, afterglow objects',
    atmosphere: 'Elegant contagion, ritual infection, controlled menace, abstract plague engineered as a clean repeatable visual strike',
    examplePrompt: 'One black relic hangs alone in a void until a cyan signal spore lands dead center, tremor rings race through the object, magenta edge-corruption ignites in one satisfying bloom, the afterglow hangs for a beat, and the relic resets to untouched black, seamless 4 to 6 second macro infection loop',
  },
  {
    id: 'tram-to-nowhere',
    name: 'Tram to Nowhere',
    colorPalette: 'Black-blue night, cyan rails, magenta-teal window reflections, brutalist gray, fog white',
    lighting: 'Urban night glow, rail underlight, fog diffusion, soft tram reflections, restrained street contrast',
    cameraPerspective: 'Street-level tracking glides, side-on transit portraits, patient liminal wides, slow disappearance framing',
    textures: 'Dark glass, wet rails, brutalist concrete, fog, shell reflections, city haze',
    motionStyle: 'Measured glide, reflection bending, fog drift, parallax crawl, vanishing into haze',
    recurringSymbols: 'Dark tram body, glowing rails, blank destination display, brutalist facades, empty windows, street fog',
    atmosphere: 'Last-transit mythology, nocturnal limbo, urban techno solitude, elegant disappearance',
    examplePrompt: 'A dark-glass tram slides through an empty black-blue city while cyan rails burn beneath it, blank windows reflecting magenta and teal across brutalist fog, seamless loop',
  },
  {
    id: 'chromatic-shard-torus',
    name: 'Chromatic Shard Torus',
    colorPalette: 'Void black, acid yellow, toxic lime, cyan edge fire, signal red misregistration, shadow blue',
    lighting: 'Hard void studio light, neon facet slashes, RGB misalignment glow, specular edge burns, zero ambient mercy',
    cameraPerspective: 'Centered torus idol shots, slow turntable rotation, macro object studies, restrained orbital drift',
    textures: 'Jagged low-poly shards, thorn prisms, chromatic splits, lacquer-black negative space, CRT-fringe ghosts',
    motionStyle: 'Torus rotation, breathing deformation, radial flutter, edge drift, seamless loop with blade-sharp poise',
    recurringSymbols: 'Spiked torus, prism wreath, RGB split contours, hollow black core, radial crowns',
    atmosphere: 'Lethal rave sculpture, aggressive synthetic precision, hypnotic artifact under total control',
    examplePrompt: 'A spiked torus of acid-yellow and toxic-lime prisms rotates in pure black, cyan and red channel ghosts peeling from the silhouette as if the object is too sharp for the image to contain, seamless loop',
  },
  {
    id: 'chromatic-shard-torus-soft-bloom',
    name: 'Chromatic Shard Torus Soft Bloom',
    colorPalette: 'Void black, softened acid yellow, translucent lime, cyan haze, pale red ghosting, velvet blue shadow',
    lighting: 'Diffused rim bloom, soft neon facet glow, pearled void contrast, chromatic mist pressure, minimal hard specular',
    cameraPerspective: 'Centered torus portraits, slow orbital hover, macro silhouette worship, front-facing calm',
    textures: 'Translucent shard faces, frosted glass thorns, RGB mist fringes, velvety gradients, powdery light',
    motionStyle: 'Breathing expansion, soft rotation, facet pulsing, afterimage drift, seamless meditative bloom',
    recurringSymbols: 'Spiked torus, translucent shard petals, chromatic ghost rim, black core, floating dust ring',
    atmosphere: 'Poisoned elegance, angelic glitch bloom, dream sculpture with a dangerous undertow',
    examplePrompt: 'A translucent torus of acid-yellow and lime shard petals hovers in black space, cyan haze wrapping the ring while pale red afterimages drag behind every edge like a poisonous halo, seamless loop',
  },
  {
    id: 'chromatic-shard-torus-techno-reactor',
    name: 'Chromatic Shard Torus Techno Reactor',
    colorPalette: 'Void black, acid yellow, toxic lime, electric cyan, machine red, gunmetal gray',
    lighting: 'Reactor-grade highlights, club side light, precise RGB offsets, metallic edge slashes, strict negative space',
    cameraPerspective: 'Centered machine studies, slow turntable framing, industrial front views, minimal orbital drift, sealed pressure composition',
    textures: 'Hard prism blades, machined shard faces, glitch contours, thin signal guide lines, clean void',
    motionStyle: 'Disciplined rotation, pulse-locked ripple waves, radial locking motions, mechanical breathing, peak-release loops',
    recurringSymbols: 'Prism torus, shard fins, reactor aperture, channel-split outline, radial machine lattice',
    atmosphere: 'Peak-time machine worship, rave-engine discipline, synthetic power under command calm',
    examplePrompt: 'A techno-reactor torus of interlocking neon blades turns in a black pressure chamber, acid-yellow and toxic-lime fins locking and unlocking around a cyan aperture with machine-red ghosts at the edges, seamless loop',
  },
  {
    id: 'chromatic-shard-torus-glitch-breach',
    name: 'Chromatic Shard Torus Glitch Breach',
    colorPalette: 'Pitch black, acid yellow, lime green, hot cyan, signal red, fractured ultramarine',
    lighting: 'Harsh edge flares, unstable channel glow, torn RGB contour light, aggressive but non-strobing contrast',
    cameraPerspective: 'Locked frontal pressure shots, center-dominant torus idol framing, macro breach studies, stable composition with instant silhouette recognition',
    textures: 'Broken shard spikes, scanline tears, doubled contours, abrasive lacquer, corrupted shadow gaps',
    motionStyle: 'Breach flexing, contour slippage, delayed echo trails, one sharp contraction-release event, exact loop closure on the original silhouette',
    recurringSymbols: 'Breach ring, duplicated contours, torn seams, black core, chromatic error echoes',
    atmosphere: 'Hostile digital elegance, high-tension artifact energy, synthetic menace sharpened into a brutal logo-like loop object',
    examplePrompt: 'An aggressive breach torus hangs in pure black with an instantly readable lime-yellow silhouette, then the ring contracts into a single violent glitch-breath, cyan-red echo contours tear away from every shard edge, the black core flares for one frame of pressure, and the object resolves back into its pristine opening shape, seamless 4 to 6 second high-impact loop',
  },
  {
    id: 'hyper-prism-frenzy-loop',
    name: 'Hyper Prism Frenzy Loop',
    colorPalette: 'Abyss black, acid cyan, molten magenta, venom lime, ultraviolet cobalt, solar tangerine, toxic gold, chrome white',
    lighting: 'Hyper-saturated halo detonations, liquid neon underglow, spectral rim fire, chrome bloom pressure, disciplined non-strobing pulse architecture',
    cameraPerspective: 'Aggressive hero framing, impossible frontal symmetry, cathedral-scale macro closeups, gravity-bent orbit locks, slow predatory push-ins that snap cleanly home',
    textures: 'Iridescent oil-slick chrome, liquid crystal skin, op-art moire glass, molten enamel fractures, lacquered plasma haze, kaleidoscopic interference bands',
    motionStyle: 'Hypnotic pressure-wave loops, prism swarms, ecstatic fold-open recoil, liquid geometry breathing, controlled overload surges with a seamless hard return',
    recurringSymbols: 'Mutant prisms, living mandalas, kaleidoscopic machine petals, shock halos, ribbon vortices, impossible totems, chromatic pattern engines',
    atmosphere: 'Maximum eyecatch spectacle, hallucinogenic luxury, ecstatic machine trance, impossible beauty under total control, addictive scroll-stopping visual seduction',
    creativeDirection: 'Push far beyond safe repetition. Invent fresh motif families, bizarre material combinations, bold silhouette hooks, and scene-specific color events in every scene. Favor never-seen-before imagery, extreme but readable contrasts, mesmerizing pattern logic, and premium hypnotic GIF moments that feel instantly addictive, unique, and unforgettable. Avoid generic portals, default abstract rings, and obvious filler symbolism unless they mutate into something truly new.',
    examplePrompt: 'A feral prism bloom erupts from a black void like a luxury hallucination, acid cyan and molten magenta petals folding inside impossible lime-gold pattern engines while chrome dust spirals through a single ecstatic recoil and the whole spectacle locks back into its first hypnotic pose, seamless eyecatch loop',
  },
  {
    id: 'sunset-seawall-graffiti',
    name: 'Sunset Seawall Graffiti',
    colorPalette: 'Hot magenta dusk, aerosol orange, mango yellow, lagoon blue, turquoise foam, bubblegum pink, sea-creature teal, cream cloud white, thick ink black',
    lighting: 'Sunset wall glow, diffuse beach haze, soft aerosol bloom, painted shadow falloff, and small seawater reflection glints',
    cameraPerspective: 'Frontal mural tableaux, side-on character parades, broad boardwalk horizontals, shallow painted depth, and billboard readability',
    textures: 'Spray-paint overspray, stucco wall grain, soft airbrush gradients, drippy enamel edges, fat black outlines, paint speckle, and sun-faded mural wear',
    motionStyle: 'Buoyant side-glide motion, raft bobbing, rubber-hose limb wobble, lazy surf drift, balloon-float arcs, and one playful payoff beat with a clean mural-pose return',
    recurringSymbols: 'Goofy sea creatures, surf dogs, flamingos, drifting bottles, rafts, smiley bulbs, cloud puffs, heart doodles, ARV spiral blooms, and signal-line inserts',
    atmosphere: 'Lowbrow seaside mural surrealism, deadpan vacation absurdity, warm aerosol calm, and mischievous street-art dream logic',
    visualIdentity: 'Sunset beach-wall graffiti built from chunky black outlines, soft spray gradients, weird friendly creature-icons, ocean-strip horizontals, and occasional ARV abstract loop inserts.',
    shortPrompt: 'Sunset seawall graffiti creature drifting across a blue water band, thick outlines, aerosol gradients, drips, and one loop-ready visual gag.',
    negativePrompt: 'No photoreal humans, gritty gang-sign cliches, dense tag lettering, corporate vector cleanliness, Pixar-style 3D mascots, hard cyberpunk chrome, horror gore, strobe, or frantic crowd clutter.',
    motionRule: 'Keep motion broad, buoyant, and legible: one rubber-hose gesture, glide, bob, blink, spill, or float event, optionally echoed by one ARV-style spiral or signal insert, then return to a strong mural pose.',
    colorRule: 'Anchor every scene in a warm sunset gradient and a simple blue water or horizon band, then accent with teal, pink, cream, and restrained black-outline contrast. Keep colors punchy but not fluorescent-chaotic.',
    obsRule: 'Preserve a bold central character or object and keep the lower third readable with simple water, boardwalk, or wall bands rather than dense detail.',
    creativeDirection: 'Treat each scene like a premium seaside mural panel with deadpan cartoon creatures, spray-paint softness, fat outlines, and one memorable visual gag. Pull structure from the ARV folder by letting abstract spirals, schematic lines, portal blooms, or diagram inserts briefly interrupt the beach-graffiti world. Do not fall back into dark archive canon, occult relics, or generic cyberpunk abstraction. Weird is welcome, but it should feel painted, sunny, and wall-readable.',
    examplePrompt: 'A teal surf-dog machine glides across a cobalt water strip under a magenta-orange sunset wall, a tiny bubblegum sidekick riding its back while a white smiley bulb flickers once and an ARV spiral halo blooms behind the outline before everything settles back into the opening mural pose, spray-paint gradients, stucco grain, thick black contour, seamless loop',
  },
  {
    id: 'stillframe-rituals',
    name: 'Stillframe Rituals',
    colorPalette: 'Black velvet, faded cream relief, cobalt blue shadow, cyan-magenta misregistration, rust amber projector glow, restrained cyan halo',
    lighting: 'Hard projector beam, archive blackout, dusty shaft light, CRT bleed, rust-amber spill, dim cyan edge leak',
    cameraPerspective: 'Locked wide shot, centered witness frame, hard first-frame readability, lower third clean for OBS overlays, no camera movement',
    textures: 'Damaged photocopy grain, scratched 16mm dust, paper fibers, black-paper tooth, xerox seams, subtle scanlines, graphite abrasion, faded ink',
    motionStyle: 'Controlled hypnotic motion, projector-flicker cadence, one dominant event, slight supporting residue, loop-ready afterimage, no hectic pacing',
    recurringSymbols: 'Paper-cut witness silhouettes, archive drawers, signal rings, relay windows, codex panels, orbit diagrams, stone-relief blocks, machine folklore emblems',
    atmosphere: 'Underground archive pressure, cosmic report logic, institutional shadow theatre, adult experimental calm, mysterious broadcast residue',
    visualIdentity: 'Dark analog archive tableaux with black paper, xerox damage, cobalt shadow, cyan-magenta bleed, rust-amber projector glow, and one dominant event inside a sparse frame.',
    shortPrompt: 'Black-paper witness silhouette in projector haze, cobalt shadow, cyan-magenta bleed, xerox afterimage, locked-frame ARV loop.',
    negativePrompt: 'No cute mascots, smiling faces, big eyes, pastel palettes, glossy toy-like 3D, anime styling, fantasy-cartoon color, decorative pseudo-sacred kitsch, readable sacred text, fake inscriptions, logos, watermarks, photoreal people, or frantic motion.',
    motionRule: 'Keep the camera locked. Use one dominant transformation or gesture, allow slight supporting residue or ghost trace, and return cleanly into the opening frame.',
    colorRule: 'Build from black velvet, faded cream relief, cobalt shadow, cyan-magenta misregistration, and rust-amber projector glow. Jade, oxidized gold, or dead CRT green may appear only as restrained accents.',
    obsRule: 'Keep the figure centered and the lower third clean for OBS overlays.',
    creativeDirection: 'Every storyboard must stay inside the ARV archive family. Use one dominant subject or event, sparse composition, damaged analog texture, hard poster readability, and controlled loop energy. Favor silhouettes, codex-panel geometry, relay windows, signal plates, archive machinery, and witness forms over generic fantasy, glossy abstraction, or decorative occult illustration. Motion may be visibly alive, but it must remain deliberate, hypnotic, and legible. No text, no logos, no mascot energy, no playful tone, and no generic cinematic wallpaper.',
    examplePrompt: 'A black-paper witness silhouette stands inside a sealed archive relay frame, projector dust cutting through cobalt shadow while cyan-magenta misregistration shivers around faded cream edges. One relay aperture opens and throws a rust-amber pulse across the figure, ghosted xerox residue lags behind the motion, and the image resolves back into its first hard pose. Damaged analog archive aesthetic, locked camera, sparse composition, lower third clean for OBS, seamless ARV loop.',
  },
  {
    id: 'enochian-sun-dance-codex',
    name: 'Glyphic Archive Procession',
    colorPalette: 'Obsidian black, faded cream, cobalt shadow, jade green, oxidized gold, terracotta dust, muted turquoise',
    lighting: 'Projector haze, jade rim spill, oxidized-gold beam breaks, cold starlight dust, rust-amber archive glow',
    cameraPerspective: 'Locked wide 16:9, lower third clean for OBS, slow deliberate drift or static tableau, centered codex-panel compositions',
    textures: 'Handmade codex paper, stone relief, woven pattern abrasion, xerox grain, scratched film dust, faded ink',
    motionStyle: 'Controlled processional footwork, mirrored silhouette turns, glyph panels pulsing like drum residue, one clean transformation per scene',
    recurringSymbols: 'Abstract glyph blocks, codex panels, sun-disc geometry, orbit grids, knot diagrams, stepped relief, seed constellations, witness silhouettes',
    atmosphere: 'Cosmic archive procession, coded mythology, ritual stillness, adult experimental reverence without spectacle',
    negativePrompt: 'No literal sacred text, readable glyphs, real ceremonial claims, tourist costume aesthetics, cheerful festival energy, stereotypes, sacrifice, conquest imagery, rainbow fantasy color, or crowd clutter.',
    soraAvoid: 'Literal sacred text, readable glyphs, real ceremonial claims, tourist costume aesthetics, cheerful festival energy, stereotypes, sacrifice, conquest imagery, rainbow fantasy color, or crowd clutter.',
    visualIdentity: 'Abstract codex-panel worlds built from glyphic rhythm, stone relief geometry, woven pattern logic, and cosmic archive systems rather than literal mythology.',
    shortPrompt: 'Damaged cosmic codex, witness silhouette, abstract glyph blocks, jade-gold accents, xerox afterimages, locked wide frame.',
    motionRule: 'Use slow deliberate procession, mirrored silhouette motion, and one structural transformation or afterimage event per scene.',
    colorRule: 'Base in obsidian black, faded cream, cobalt shadow, jade, oxidized gold, terracotta dust, and muted turquoise. Avoid candy color or fantasy glow.',
    obsRule: 'Keep the lower third dark and uncluttered, with the main action in the middle and upper frame.',
    creativeDirection: 'Use Mesoamerican and Andean references only as abstract structural inspiration: glyphic rhythm, stone relief geometry, codex-panel composition, woven pattern logic, sun-disc geometry, and celestial archive systems. Do not stage literal historical reenactment or pseudo-sacred illustration. Each scene gets one dominant motion event and one symbolic transformation.',
    examplePrompt: 'A damaged cosmic codex opens from projector haze, black paper and faded cream relief holding one witness silhouette while abstract glyph blocks pulse like drum residue and a rust-amber star map duplicates into cyan-magenta afterimages, locked wide, lower third clean, seamless loop.',
  },
];

const RETIRED_PRESET_IDS = new Set([
  'style-taste-archive',
  'archive-iris-kaleidoscope',
  'mirror-witness-duet',
  'ancestral-halo-witness',
  'stillframe-rituals',
  'enochian-sun-dance-codex',
]);

export const PRESETS: StylePreset[] = ALL_PRESETS.filter((preset) => !RETIRED_PRESET_IDS.has(preset.id));

export const CURATED_PRESET_IDS = [
  'micro-city-on-vinyl',
  'bass-weather-laboratory',
  'cable-monastery',
  'deep-server-reef',
  'glass-engine-breathing',
  'magnetic-desert-crossing',
  'signal-ring-eclipse',
  'operator-after-midnight',
  'dead-channel-ministry',
  'sunset-seawall-graffiti',
  'chromatic-shard-torus',
  'chromatic-shard-torus-soft-bloom',
  'chromatic-shard-torus-techno-reactor',
  'chromatic-shard-torus-glitch-breach',
] as const;

export const CURATED_PRESETS: StylePreset[] = CURATED_PRESET_IDS
  .map((presetId) => PRESETS.find((preset) => preset.id === presetId))
  .filter((preset): preset is StylePreset => Boolean(preset));